# [START runtime]
runtime: go
api_version: go1
vm: true
# [END runtime]

# [START resources]
resources:
  cpu: .5
  memory_gb: 1
  disk_size_gb: 10
# [END resources]

# [START scaling]
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.5
# [END scaling]

handlers:
- url: /.*
  script: _go_app
